# .github/workflows/release.yml

name: Release and Push to ECR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_NAME: startup_keycloak_ecr
        run: |
          echo "Releasing version ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.ref_name }}"
          docker build -t ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.ref_name }} .
          docker push "${ECR_REGISTRY}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.ref_name }}"
